#!/bin/bash -ex

source /usr/sbin/get_hive_home.sh

sudo -E -u hive nohup ${HIVE_HOME}/bin/hiveserver2 > /var/log/${HIVE_PACKAGE}/hiveserver2.out 2>&1  &
sleep 60 # wait for hive server to startup completely
