#! /bin/bash

set -ex

VERSION_FULL=$1
PATCH_FILE=$2
VERSION_SHORT=$(echo ${VERSION_FULL} | head -c 3)
VERSION_NO_DOT=$(echo ${VERSION_SHORT} | tr -d .)

cd /usr/src
wget https://www.python.org/ftp/python/${VERSION_FULL}/Python-${VERSION_FULL}.tar.xz
tar -xf Python-${VERSION_FULL}.tar.xz

if [ "" != "$PATCH_FILE" ]; then
    cp -vf $PATCH_FILE Python-${VERSION_FULL}/Modules/Setup.dist
fi

cd Python-${VERSION_FULL}
LDFLAGS="-Wl,-rpath=/usr/local/openssl11/lib" ./configure --prefix=/usr/local/python${VERSION_NO_DOT} --with-openssl=/usr/local/openssl11 --with-system-ffi
make altinstall
ln -s /usr/local/python${VERSION_NO_DOT}/bin/*${VERSION_SHORT}* /usr/local/bin
cd ..
rm -rf Python-${VERSION_FULL}*
virtualenv --python=python${VERSION_SHORT} /envs/h2o_env_python${VERSION_SHORT}
source /envs/h2o_env_python${VERSION_SHORT}/bin/activate
pip install pip wheel setuptools --upgrade
deactivate
