FROM registry.access.redhat.com/ubi8/ubi-minimal

ARG H2O_VERSION
# Mandatory labels required by Red Hat for certification
LABEL "name"="H2O Open Source Machine Learning"
LABEL "vendor"="H2O.ai"
LABEL "version"=${H2O_VERSION}
LABEL "release"=${H2O_VERSION}
LABEL "summary"="H2O Open Source Machine Learning platform"
LABEL "description"="H2O is an Open Source, Distributed, Fast & Scalable Machine Learning Platform: Deep Learning, Gradient Boosting (GBM) & XGBoost, Random Forest, Generalized Linear Modeling (GLM with Elastic Net), K-Means, PCA, Generalized Additive Models (GAM), RuleFit, Support Vector Machine (SVM), Stacked Ensembles, Automatic Machine Learning (AutoML), etc."

# Install OpenJDK 11
# The Java installed must properly recognize container resource limits
RUN microdnf install java-11-openjdk
RUN microdnf clean all

# Copy H2O-3 artifact into the container
RUN mkdir -p /opt/h2oai/h2o-3/
COPY h2o.jar /opt/h2oai/h2o-3/

# Copy project's license into the container (required by Red Hat for certification)
RUN mkdir /licenses
COPY LICENSE /licenses/

# By default, run H2O and allocate only 50 percent of memory available to the JVM, the rest remains free for XGBoost
# Overridable by the user
CMD java -XX:+UseContainerSupport -XX:MaxRAMPercentage=50 -jar /opt/h2oai/h2o-3/h2o.jar
