FROM 353750902984.dkr.ecr.us-east-1.amazonaws.com/thirdparty-chainguard-openjdk:v17-dev-latest

ARG H2O_VERSION
# Mandatory labels required by Red Hat for certification
LABEL "name"="H2O Open Source Machine Learning"
LABEL "vendor"="H2O.ai"
LABEL "version"=${H2O_VERSION}
LABEL "release"=${H2O_VERSION}
LABEL "summary"="H2O Open Source Machine Learning platform"
LABEL "description"="H2O is an Open Source, Distributed, Fast & Scalable Machine Learning Platform: Deep Learning, Gradient Boosting (GBM) & XGBoost, Random Forest, Generalized Linear Modeling (GLM with Elastic Net), K-Means, PCA, Generalized Additive Models (GAM), RuleFit, Support Vector Machine (SVM), Stacked Ensembles, Automatic Machine Learning (AutoML), etc."

# Switch to root to install packages (Chainguard runs as non-root by default)
USER root

# Install libgomp - to enable XGBoost multithreading
RUN apk add --no-cache libgomp

# Copy H2O-3 artifact into the container
RUN mkdir -p /opt/h2oai/h2o-3/
COPY h2o.jar /opt/h2oai/h2o-3/

# Extract native XGBoost libraries to avoid extract on H2O boot-up
RUN mkdir /opt/h2oai/h2o-3/xgb_lib_dir \
    && java -cp /opt/h2oai/h2o-3/h2o.jar water.tools.XGBoostLibExtractTool /opt/h2oai/h2o-3/xgb_lib_dir

# Copy project's license into the container (required by Red Hat for certification)
RUN mkdir /licenses
COPY LICENSE /licenses/

# By default, run H2O and allocate only 50 percent of memory available to the JVM, the rest remains free for XGBoost
# Overridable by the user
CMD java -Djava.library.path=/opt/h2oai/h2o-3/xgb_lib_dir -XX:+UseContainerSupport -XX:MaxRAMPercentage=50 -jar /opt/h2oai/h2o-3/h2o.jar

# Switch to nonroot user (Chainguard default: UID 65532)
USER 65532
