#! /bin/bash

set -e
set -x

if [ -z ${JENKINS_GROUP_NAME} ]; then
    JENKINS_GROUP_NAME=jenkins
fi

if [ -z ${JENKINS_USER_NAME} ]; then
    JENKINS_USER_NAME=jenkins
fi

groupadd -g ${JENKINS_GID} ${JENKINS_GROUP_NAME}
useradd ${JENKINS_USER_NAME} -m -u ${JENKINS_UID} -g ${JENKINS_GROUP_NAME}