#! /bin/bash

set -e
set -x

virtualenv -p python3.5 /envs/h2o_env_python3.5
chmod a+w -R /envs/h2o_env_python3.5
source /envs/h2o_env_python3.5/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools
wget https://raw.githubusercontent.com/h2oai/h2o-3/${H2O_BRANCH}/h2o-py/test-requirements.txt
pip install -r test-requirements.txt
rm test-requirements.txt
