#'
#' Quadratically Regularized PCA Model in H2O
#'
#' Principal components analysis with quadratic regularization of an H2O dataset.
#'
#'
#' @param training_frame An \linkS4class{H2OFrame} object containing the
#'        variables in the model.
#' @param x (Optional) A vector containing the data columns on
#'        which k-means operates.
#' @param k The rank of the resulting decomposition. Must be between 1 and
#'        1e7 inclusive. k may be omitted if the user specifies the
#'        initial centers in the init parameter. If k is not omitted,
#'        in this case, then it should be equal to the number of
#'        user-specified centers.
#' @param destination_key (Optional) The unique hex key assigned to the
#'        resulting model. Automatically generated if none is provided.
#' @param max_iterations The maximum number of iterations to run alternating
#'        minimization. Must be between 0 and 1e6 inclusive.
#' @param transform A character string that indicates how the training data
#'        should be transformed before running PCA. Possible values are "NONE":
#'        for no transformation, "DEMEAN": for subtracting the mean of each
#'        column, "DESCALE": for dividing by the standard deviation of each
#'        column, "STANDARDIZE": for demeaning and descaling, and "NORMALIZE": 
#'        for demeaning and dividing each column by its range (max - min).
#' @param init A character string that selects the initial set of k cluster
#'        centers. Possible values are "PlusPlus": for k-means++ initialization, 
#'        or a user-specified initial Y as a matrix, data.frame, H2OFrame, or list 
#'        of vectors.
#' @param seed (Optional) Random seed used to initialize the cluster centroids with
#'        k-means++ initialization.
#' @return Returns an object of class \linkS4class{H2ODimReductionModel}.
#' @examples
#' library(h2o)
#' localH2O <- h2o.init()
#' arrestsPath <- system.file("extdata", "australia.csv", package="h2o")
#' arrests.hex <- h2o.uploadFile(localH2O, path = arrestsPath)
#' h2o.prcomp(training_frame = arrests.hex, k = 4, max_iterations = 100)
h2o.prcomp <- function(training_frame, x, k, center = TRUE, scale. = FALSE,
                       ## AUTOGENERATED PARAMETERS ##     # these defaults are not read by h2o
                       destination_key,                   # h2o generates its own default parameters
                       gamma = 0,
                       max_iterations = 1000,
                       init = "PlusPlus",
                       seed)
{
  # Required args: training_frame
  if( missing(training_frame) ) stop ("argument \"training_frame\" is missing, with no default")

  # Training_frame may be a key or an H2OFrame object
  if (!inherits(training_frame, "H2OFrame"))
    tryCatch(training_frame <- h2o.getFrame(training_frame),
             error = function(err) {
               stop("argument \"training_frame\" must be a valid H2OFrame or key")
             })

  .pca.map <- c("x" = "ignored_columns")

  # Gather user input
  parms <- as.list(match.call()[-1L])
  names(parms) <- lapply(names(parms), function(i) { if( i %in% names(.pca.map) ) i <- .pca.map[[i]]; i })

  if( !(missing(x)) ) parms[["ignored_columns"]] <- .verify_datacols(training_frame, x)$cols_ignore

  # Check if init is an acceptable set of user-specified starting points
  if( is.data.frame(init) || is.matrix(init) || is.list(init) || inherits(init, "H2OFrame") ) {
    parms[["init"]] <- "User"
    # Convert user-specified starting points to H2OFrame
    if( is.data.frame(init) || is.matrix(init) || is.list(init) ) {
      if( !is.data.frame(init) && !is.matrix(init) ) init <- t(as.data.frame(init))
      init <- as.h2o(init, training_frame@conn)
    }
    parms[["user_points"]] <- init
    # Set k
    if( !(missing(k)) && k!=as.integer(nrow(init)) ) {
      warning("Parameter k is not equal to the number of user-specified starting points. Ignoring k. Using specified starting points.")
    }
    parms[["user_points"]] <- parms[["user_points"]]@key
    parms[["k"]] <- as.integer(nrow(init))
  }
  else if ( is.character(init) ) { # PlusPlus
    parms[["user_points"]] <- NULL
  }
  else{
    stop ("argument init must be set to PlusPlus, or a valid set of user-defined starting points.")
  }
  
  if(center && scale.)
    parms[["transform"]] <- "STANDARDIZE"
  else if(center && !scale.)
    parms[["transform"]] <- "DEMEAN"
  else if(!center && scale.)
    parms[["transform"]] <- "DESCALE"
  else
    parms[["transform"]] <- "NONE"
  parms[["center"]] <- NULL
  parms[["scale."]] <- NULL

  # Error check and build model
  .h2o.createModel(training_frame@conn, 'pca', parms, parent.frame())
}
