# This file is auto-generated by h2o-3/h2o-bindings/bin/gen_R.py
# Copyright 2016 H2O.ai;  Apache License Version 2.0 (see LICENSE for details) 
#'
# -------------------------- Target Encoder -------------------------- #
#'
#' Transformation of a categorical variable with a mean value of the target variable
#'
#' @param training_frame Id of the training data frame.
#' @param target_column Target column for the encoding
#' @param encoded_columns Columnds to encode.
#' @param k Parameter 'k' used for blending (if enabled). Blending is to be enabled separately using the 'blending'
#'        parameter. Defaults to 0.
#' @param f Parameter 'f' used for blending (if enabled). Blending is to be enabled separately using the 'blending'
#'        parameter. Defaults to 0.
#' @param data_leakage_handling Data leakage handling strategy. Default to None. Must be one of: "None", "KFold", "LeaveOneOut".
#' @param model_id Destination id for this model; auto-generated if not specified.
#' @param fold_column Column with cross-validation fold index assignment per observation.
#' @examples
#' \dontrun{
#' # library(h2o)
#' # h2o.init()
#' #
#' # Create a target encoder
#' # target_encoder <- h2o.targetencoder(training_frame = data, encoded_columns= encoded_columns,
#' # target_column = "survived", fold_column = "pclass", data_leakage_handling = "KFold")
#' #
#' # Apply the Target Encoder transformation
#' # encoded_data <- h2o.transform(target_encoder, data)
#' }
#' @export
h2o.targetencoder <- function(training_frame,
                              target_column,
                              encoded_columns,
                              k = 0,
                              f = 0,
                              data_leakage_handling = c("None", "KFold", "LeaveOneOut"),
                              model_id = NULL,
                              fold_column = NULL)
{
  # Validate required training_frame first and other frame args: should be a valid key or an H2OFrame object
  training_frame <- .validate.H2OFrame(training_frame, required=TRUE)

  # Validate other required args
  if(missing(training_frame)) stop("Training frame must be specified.")
  if(missing(target_column)) stop("Target column must be specified.")
  if(missing(encoded_columns)) stop("Encoded columns must be specified.")

  # Build parameter list to send to model builder
  parms <- list()
  parms$response_column <- target_column
  parms$training_frame <- training_frame

  if (!missing(encoded_columns))
    parms$encoded_columns <- encoded_columns
  if (!missing(target_column))
    parms$target_column <- target_column
  if (!missing(k))
    parms$k <- k
  if (!missing(f))
    parms$f <- f
  if (!missing(data_leakage_handling))
    parms$data_leakage_handling <- data_leakage_handling
  if (!missing(model_id))
    parms$model_id <- model_id
  if (!missing(fold_column))
    parms$fold_column <- fold_column

  # Error check and build model
  model <- .h2o.modelJob('targetencoder', parms, h2oRestApiVersion=3, verbose=FALSE)
  return(model)
}
