#! /bin/bash

set -x
set -e

if [[ ! ${H2O_BRANCH} ]]; then
 echo "H2O_BRANCH must be set"
 exit 1
fi

PYTHON_VERSION='3.5'
R_VERSION='3.4.1'
JAVA_VERSION='8'

# cd home
cd

echo "###### Activate Python ${PYTHON_VERSION} ######"
. /envs/h2o_env_python${PYTHON_VERSION}/bin/activate

echo "###### Activate R 3.4.1 ######"
activate_R_${R_VERSION}

echo "###### Activate Java 8 ######"
/usr/opt/activate_java_8

echo '###### Clone H2O-3 ######'
git clone https://github.com/h2oai/h2o-3
cd h2o-3
git checkout ${H2O_BRANCH}

echo '###### Build H2O-3 ######'
printenv
make -f scripts/jenkins/Makefile.jenkins warmup-caches

echo '###### Cleanup ######'
rm -rf ~/h2o-3
