#!/bin/bash -ex

# Script for installing all R versions specified as comma separated list
# in ${1} or in ${R_VERSIONS}.

if [[ ! ${H2O_BRANCH} ]]; then
 echo "H2O_BRANCH must be set"
 exit 1
fi

VERSIONS_TO_INSTALL=${1}
if [[ ! -n ${VERSIONS_TO_INSTALL} ]]; then
  VERSIONS_TO_INSTALL=${PYTHON_VERSIONS}
fi
if [[ ! -n ${VERSIONS_TO_INSTALL} ]]; then
  echo "Either PYTHON_VERSIONS must be set or provide and argument containing required versions"
  exit 1
fi

# Download requirements files from GitHub
wget -nv https://raw.githubusercontent.com/h2oai/h2o-3/${H2O_BRANCH}/h2o-py/test-requirements.txt
wget -nv https://raw.githubusercontent.com/h2oai/h2o-3/${H2O_BRANCH}/h2o-py/docs-requirements.txt

IFS=',' read -r -a array <<< ${VERSIONS_TO_INSTALL}
for python_version in "${array[@]}"; do
  echo "###### Installing Python ${python_version} ######"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -y install python${python_version} python${python_version}-dev
  if [[ "3.7 3.8 3.9" == *${python_version}* ]]; then
      DEBIAN_FRONTEND=noninteractive apt-get -y install python${python_version}-distutils
  fi
  apt-get clean
  rm -rf /var/cache/apt/*

  echo "###### Creating Virtualenv for Python ${python_version} ######"
  mkdir -p /envs/h2o_env_python${python_version}
  chmod a+w -R /envs/h2o_env_python${python_version}
  su jenkins -c "virtualenv -p python${python_version} /envs/h2o_env_python${python_version}"

  echo "###### Installing dependencies for Python ${python_version} ######"
  su jenkins -c ". /envs/h2o_env_python${python_version}/bin/activate && pip uninstall setuptools -y && pip install setuptools" # resinstalling setuptools fixes install issues for sphinx-osexample
  su jenkins -c ". /envs/h2o_env_python${python_version}/bin/activate && grep -v \"^#\" test-requirements.txt | sed -r 's/(.*)/\"\\1\"/' | xargs -n 1 -L 1 pip install"
  if [[ $python_version == 3.* ]]; then
    su jenkins -c ". /envs/h2o_env_python${python_version}/bin/activate && grep -v \"^#\" docs-requirements.txt | sed -r 's/(.*)/\"\\1\"/' | xargs -n 1 -L 1 pip install"    
  fi
  su jenkins -c "mkdir -p ~/.config/matplotlib/ && echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc"
done

rm test-requirements.txt
