#! /bin/bash

set -e
set -x

JAVA_INSTALL_VERSION=161
MAGIC_B_NUM=12
JAVA_INSTALL_LINK_HASH=2f38c3b165be4555a1fa6e98c45e0808
JAVA_INSTALL_PATH=/usr/opt/java-8-${JAVA_INSTALL_VERSION}/

mkdir -p ${JAVA_INSTALL_PATH}
cd ${JAVA_INSTALL_PATH}

echo "Installing Java 8u${JAVA_INSTALL_VERSION} to $(pwd)"

curl -j -k -L -H "Cookie: oraclelicense=accept-securebackup-cookie" \
  http://download.oracle.com/otn-pub/java/jdk/8u${JAVA_INSTALL_VERSION}-b${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz > jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz

tar zxvf jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz
rm jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz

cd jdk*
mkdir -p /usr/lib/jvm/
echo "Symlinking /usr/lib/jvm/java-8-oracle/ -> $(pwd)"
ln -s -f $(pwd) /usr/lib/jvm/java-8-oracle
