#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='11'
JAVA_INSTALL_VERSION='11'
MAGIC_NUM=28
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=https://download.java.net/java/early_access/jdk${JAVA_INSTALL_VERSION}/${MAGIC_NUM}/BCL/jdk-${JAVA_INSTALL_VERSION}+${MAGIC_NUM}_linux-x64_bin.tar.gz
