#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='11'
JAVA_INSTALL_VERSION=3
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
JDK_FILE=/tmp/jdk-11.0.3_linux-x64_bin.tar.gz
