#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='8'
JAVA_INSTALL_VERSION=191
MAGIC_B_NUM=12
JAVA_INSTALL_LINK_HASH=2787e4a523244c269598db4e85c51e0c
JAVA_INSTALL_PATH=/usr/opt/java-8-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/8u${JAVA_INSTALL_VERSION}-b${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz
