#! /bin/bash
JAVA_INSTALL_VERSION_MAJOR='13'
JAVA_BUILD_NUMBER=33
JAVA_INSTALL_VERSION=eap
JAVA_INSTALL_LINK_HASH=5b8a42f3905b406298b72d750b6919f6
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=https://download.java.net/java/GA/jdk${JAVA_INSTALL_VERSION_MAJOR}/${JAVA_INSTALL_LINK_HASH}/${JAVA_BUILD_NUMBER}/GPL/openjdk-${JAVA_INSTALL_VERSION_MAJOR}_linux-x64_bin.tar.gz
