#! /bin/bash
JAVA_INSTALL_VERSION_MAJOR='12'
JAVA_INSTALL_VERSION=2
MAGIC_B_NUM=10
JAVA_INSTALL_LINK_HASH=e482c34c86bd4bf8b56c0b35558996b9
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/${JAVA_INSTALL_VERSION_MAJOR}.0.${JAVA_INSTALL_VERSION}+${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-${JAVA_INSTALL_VERSION_MAJOR}.0.${JAVA_INSTALL_VERSION}_linux-x64_bin.tar.gz
