#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='10'
JAVA_INSTALL_VERSION='10.0.2'
MAGIC_NUM=13
JAVA_INSTALL_LINK_HASH=19aef61b38124481863b1413dce1855f
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/${JAVA_INSTALL_VERSION}+${MAGIC_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-${JAVA_INSTALL_VERSION}_linux-x64_bin.tar.gz
