#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='21'
JAVA_INSTALL_VERSION=0
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
JDK_FILE=/tmp/jdk-21.0.0_linux-x64_bin.tar.gz
