#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='10'
JAVA_INSTALL_VERSION=2
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
JDK_FILE=/tmp/jdk-10.0.2_linux-x64_bin.tar.gz