#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='8'
JAVA_INSTALL_VERSION=201
MAGIC_B_NUM=09
JAVA_INSTALL_LINK_HASH=42970487e3af4f5aa5bca3f542482c60
JAVA_INSTALL_PATH=/usr/opt/java-8-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/8u${JAVA_INSTALL_VERSION}-b${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz
