#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='8'
JAVA_INSTALL_VERSION=181
MAGIC_B_NUM=13
JAVA_INSTALL_LINK_HASH=96a7b8442fe848ef90c96a2fad6ed6d1
JAVA_INSTALL_PATH=/usr/opt/java-8-${JAVA_INSTALL_VERSION}/
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/8u${JAVA_INSTALL_VERSION}-b${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-8u${JAVA_INSTALL_VERSION}-linux-x64.tar.gz