#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='15'
JAVA_INSTALL_VERSION=2
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
JDK_FILE=/tmp/jdk-15.0.2_linux-x64_bin.tar.gz
