#!/bin/bash -ex

# init mysql database for metastore

rm -rf /var/lib/mysql
mkdir -p /var/lib/mysql /var/run/mysqld
chown -R mysql:mysql /var/lib/mysql /var/run/mysqld
chmod 777 /var/run/mysqld

mysqld --initialize-insecure --user=mysql
service mysql start

echo "CREATE DATABASE metastore;" | mysql
/usr/bin/mysqladmin -u root password 'root'

source /usr/sbin/get_hive_home.sh
${HIVE_HOME}/bin/schematool -initSchema -dbType mysql
