FROM nvidia/cuda:8.0-devel-ubuntu14.04
MAINTAINER h2oai "h2o.ai"

ARG JENKINS_UID='2117'
ARG JENKINS_GID='2117'
ARG H2O_BRANCH='h2o3'
ARG PYTHON_VERSIONS='3.5,3.6,3.7,3.8'

# Install required packages
RUN \
    apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:deadsnakes && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y zip wget git unzip python3 python3-dev \
        python3-pip gcc-5 g++-5 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

COPY xgb/common/sbin/install_java xgb_build/scripts/install_python_version_ubuntu /usr/sbin/

# Install java
COPY jdk1.8.0_171.zip /usr/local/lib/
RUN \
    chmod a+x /usr/sbin/install_java && \
    sync && \
    /usr/sbin/install_java

ENV JAVA_VERSION '8'
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
ENV PATH ${JAVA_HOME}/bin:${PATH}

# Install all Python versions
RUN \
    pip3 install virtualenv && \
    chmod a+x /usr/sbin/install_python_version_ubuntu && \
    sync && \
    /usr/sbin/install_python_version_ubuntu

# Install Apache Maven
RUN \
    cd opt && \
    wget http://www-us.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip && \
    unzip apache-maven-3.5.4-bin.zip && \
    rm apache-maven-3.5.4-bin.zip
ENV PATH /opt/apache-maven-3.5.4/bin:${PATH}

# Install CMake
ENV CMAKE_VERSION '3.18'
ENV CMAKE_PATCH '.2'
RUN \
    wget http://www.cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.${CMAKE_PATCH}.tar.gz && \
    tar -xvzf cmake-${CMAKE_VERSION}.${CMAKE_PATCH}.tar.gz && \
    cd cmake-${CMAKE_VERSION}.${CMAKE_PATCH}/ && \
    ./configure && \
    make && \
    make install && \
    cd .. && \
    rm -rf cmake-${CMAKE_VERSION}.${CMAKE_PATCH} && \
    if [ "$(cmake --version | head -1)" != 'cmake version ${CMAKE_VERSION}.${CMAKE_PATCH}' ]; then exit 1; fi

# Install hub
RUN \
    wget https://github.com/github/hub/releases/download/v2.2.9/hub-linux-amd64-2.2.9.tgz && \
    tar zxf hub-linux-amd64-2.2.9.tgz && \
    rm -rf hub-linux-amd64-2.2.9.tgz && \
    cd hub-linux-amd64-* && \
    ./install

# Add the Jenkins user
RUN \
    groupadd -g ${JENKINS_GID} jenkins && \
    useradd jenkins -m -u ${JENKINS_UID} -g jenkins
