---
title: "Basics of H2O"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About H2O

H2O.ai is focused on bringing AI to businesses through software.  Its flagship product is H2O, the leading open source platform that makes it easy for financial services, insurance companies, and healthcare companies to deploy AI and deep learning to solve complex problems.

Using in-memory compression, H2O handles billions of data rows in-memory, even with a small cluster.  To make it easier for non-engineers to create complete analytic workflows, H2O’s platform includes interfaces for R, Python, Scala, Java, JSON, and CoffeeScript/JavaScript, as well as a built-in web interface, Flow.  H2O is designed to run in standalone mode, on Hadoop, or within a Spark Cluster, and typically deploys within minutes.

H2O includes many common machine learning algorithms, such as generalized linear modeling (linear regression, logistic regression, etc.), Naïve Bayes, principal components analysis, k-means clustering, word2vec, and XGBoost.  H2O implements best-in-class algorithms at scale, such as distributed random forest, gradient boosting, and deep learning.  H2O also includes a Stacked Ensembles method, which finds the optimal combination of a collection of prediction algorithms using a process known as ”stacking.” With H2O, customers canbuild thousands of models and compare the results to get the best predictions.
