#! /bin/bash

set -e -x

sudo -E -u hdfs hadoop fs -mkdir -p /user/hive/warehouse
sudo -E -u hdfs hadoop fs -chmod a+w /user/hive/warehouse
sudo -E -u hdfs hadoop fs -chmod a+w /tmp

cd /home/hive
if [ "${HIVE_VERSION}" = '2.1.1-cdh6.0.0' ]; then
    service hive-server2 start
else
    sudo -E -u hive nohup ${HIVE_HOME}/bin/hiveserver2 > /home/hive/hive.log & sleep 15
fi