// Generated by CoffeeScript 1.5.0
(function() {
  var module;

  module = angular.module('swing.filters');

  module.filter("humanizeFilesize", function() {
    return function(input) {
      return humanize.filesize(input);
    };
  });

}).call(this);
