#! /bin/bash

set -e
set -x

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update
apt-get install -y \
    wget gcc unzip tar \
    python3.5-dev git python-pip python-virtualenv \
    nodejs npm libkrb5-dev
