#! /bin/bash

set -e
set -x

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y software-properties-common
add-apt-repository -y ppa:deadsnakes/ppa
apt-get update
apt-get install -y default-libmysqlclient-dev # has to be done in separate step otherwise the install fails
apt-get install -y \
    wget gcc python3.5-dev git python-pip python-virtualenv \
    unzip tar nodejs npm libkrb5-dev
