#! /bin/bash

set -e
set -x

JDK_FILE='jdk-8u171-linux-x64.tar.gz'
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
"http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/${JDK_FILE}"
tar zxvf ${JDK_FILE}
rm ${JDK_FILE}

cd jdk*
mkdir -p /usr/lib/jvm/
echo "Symlinking /usr/lib/jvm/java-8-oracle/ -> $(pwd)"
ln -s -f $(pwd) /usr/lib/jvm/java-8-oracle
