#! /bin/bash

set -e

if [[ $(echo ${SUPPRESS_H2O_DOWNLOAD} | tr -s '[:upper:]' '[:lower:]') != 'true' ]]; then
    NIGHTLY_BUILD_ID=$(curl -s http://h2o-release.s3.amazonaws.com/h2o/master/latest.html | egrep -o "[0-9]{4,}")
    echo "Downloading H2O with build ID ${NIGHTLY_BUILD_ID}"
    su - h2o -c "wget http://h2o-release.s3.amazonaws.com/h2o/master/${NIGHTLY_BUILD_ID}/h2o-3.15.0.${NIGHTLY_BUILD_ID}-${DISTRIBUTION}${VERSION}.zip"
    su - h2o -c 'unzip h2o*.zip'
    su - h2o -c 'rm h2o*.zip'
    cd /home/h2o/h2o*/python
    pip install h2o-*.whl
else
    echo "Download of H2O is suppressed"
fi