ARG FROM_VERSION
FROM harbor.h2o.ai/opsh2oai/h2o-3/dev-python-base:${FROM_VERSION}

ARG H2O_BRANCH=master
ARG PYTHON_VERSION
ENV PYTHON_VERSION=${PYTHON_VERSION}

RUN \
    /tmp/install_python_version ${PYTHON_VERSION}
