ARG FROM_VERSION
ARG FROM_IMAGE=harbor.h2o.ai/opsh2oai/h2o-3/dev-jdk-others-base
FROM ${FROM_IMAGE}:${FROM_VERSION}

ARG INSTALL_JAVA_VERSION
ENV JAVA_VERSION=${INSTALL_JAVA_VERSION}
COPY scripts/install_java_version scripts/install_java_version_local \
     scripts/java-${JAVA_VERSION}-vars.sh \
     scripts/build-h2o-3 \
     jdk-${JAVA_VERSION}*.tar.gz \
     jdk1.${JAVA_VERSION}*.zip \
     /tmp/
RUN \
    chmod +x /tmp/install_java_version /tmp/java-${JAVA_VERSION}-vars.sh && \
    sync && \
    if [ "${JAVA_VERSION}" = '8' ] || [ "${JAVA_VERSION}" = '10' ] || [ "${JAVA_VERSION}" = '11' ] || \
        [ "${JAVA_VERSION}" = '12' ] || [ "${JAVA_VERSION}" = '13' ] || [ "${JAVA_VERSION}" = '14' ] || \
        [ "${JAVA_VERSION}" = '15' ] || [ "${JAVA_VERSION}" = '16' ] || [ "${JAVA_VERSION}" = '17' ] || \
        [ "${JAVA_VERSION}" = '21' ]; then \
        /tmp/install_java_version_local ${JAVA_VERSION} /tmp/java-${JAVA_VERSION}-vars.sh; \
    else \
        /tmp/install_java_version ${JAVA_VERSION} /tmp/java-${JAVA_VERSION}-vars.sh; \
    fi && \
    rm /tmp/install_java_* \
        /tmp/java-${JAVA_VERSION}-vars.sh \
        /tmp/jdk* && \
    chmod a+w /usr/lib/jvm/

ENV \
  JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-oracle \
  PATH=/usr/lib/jvm/java-${JAVA_VERSION}-oracle/bin:${PATH}

# Warmup
ARG H2O_BRANCH=master
USER jenkins
RUN BUILD_HADOOP=false /tmp/build-h2o-3
USER root
