ARG FROM_VERSION
FROM harbor.h2o.ai/opsh2oai/h2o-3/dev-base:${FROM_VERSION}

ENV NODE_MAJOR '16'

RUN \
    add-apt-repository -y ppa:deadsnakes && \
    apt-get update && apt-get install -y ca-certificates curl gnupg &&  mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --no-tty --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
    echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        python3-virtualenv libkrb5-dev nodejs && \
    apt-get clean && \
    rm -rf /var/cache/apt/*

COPY scripts/install_java_version scripts/install_python_version /tmp/
ENV PYTHON_VERSION=3.7
ARG H2O_BRANCH='master'
RUN \
    chmod +x /tmp/install_java_version /tmp/install_python_version && \
    sync && \
    /tmp/install_python_version ${PYTHON_VERSION} && \
    rm /tmp/install_python_version
