ARG GPU_SUFFIX=''
ARG FROM_VERSION
ARG GRADLE_VERSION
FROM harbor.h2o.ai/opsh2oai/h2o-3/dev-build-hadoop-gradle-${GRADLE_VERSION}${GPU_SUFFIX}:${FROM_VERSION}

# Install s3cmd
ENV S3_CMD_VERSION '2.1.0'
RUN \
    cd /opt/ && \
    pip install python-dateutil==2.8.1 && \
    pip install -e git+https://github.com/s3tools/s3cmd.git@v${S3_CMD_VERSION}#egg=s3cmd --src=./s3cmd-{S3_CMD_VERSION}

# Install conda
RUN \
    curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh && \
    bash /tmp/miniconda.sh -bfp /usr/local && \
    rm /tmp/miniconda.sh && \
    conda install -y anaconda-client conda-build && \
    conda update conda && \
    conda clean --all --yes

ENV PATH /opt/conda/bin:$PATH
ENV GRADLE_USER_HOME=/home/jenkins/.gradle
