FROM ubuntu:latest

# Universal image used to run both H2O or python scripts used for clustering and testing
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
	&& apt-get install default-jdk curl python3 python-is-python3 python3-pip -y \
    && pip3 install kubernetes requests argparse \
    && curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl


RUN rm /var/lib/apt/lists -rf

CMD ls -lah && java -jar h2o.jar
