ARG FROM_VERSION
ARG FROM_IMAGE=harbor.h2o.ai/opsh2oai/h2o-3/dev-jdk-others-base
FROM ${FROM_IMAGE}:${FROM_VERSION}

ARG INSTALL_JAVA_VERSION
ENV JAVA_VERSION=${INSTALL_JAVA_VERSION}
COPY scripts/install_java_version scripts/install_java_version_local scripts/java-${JAVA_VERSION}-vars.sh \
     jdk-15.0.2_linux-x64_bin.tar.gz \
     jdk-14.0.2_linux-x64_bin.tar.gz \
     jdk-13.0.2_linux-x64_bin.tar.gz \
     jdk-12.0.2_linux-x64_bin.tar.gz \
     jdk-11.0.3_linux-x64_bin.tar.gz \
     jdk-10.0.2_linux-x64_bin.tar.gz \
     jdk1.8.0_171.zip \
     /tmp/
RUN \
    chmod +x /tmp/install_java_version /tmp/java-${JAVA_VERSION}-vars.sh && \
    sync && \
    if [ "${JAVA_VERSION}" = '8' ] || [ "${JAVA_VERSION}" = '10' ] || [ "${JAVA_VERSION}" = '11' ] || \
        [ "${JAVA_VERSION}" = '12' ] || [ "${JAVA_VERSION}" = '13' ] || [ "${JAVA_VERSION}" = '14' ] || \
        [ "${JAVA_VERSION}" = '15' ]; then \
        /tmp/install_java_version_local ${JAVA_VERSION} /tmp/java-${JAVA_VERSION}-vars.sh; \
    else \
        /tmp/install_java_version ${JAVA_VERSION} /tmp/java-${JAVA_VERSION}-vars.sh; \
    fi && \
    rm /tmp/install_java_version \
        /tmp/install_java_version_local \
        /tmp/java-${JAVA_VERSION}-vars.sh \
        /tmp/jdk-*.tar.gz
        /tmp/jdk1.8.0_171.zip && \
    chmod a+w /usr/lib/jvm/

ENV \
  JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-oracle \
  PATH=/usr/lib/jvm/java-${JAVA_VERSION}-oracle/bin:${PATH}

# Warmup
USER jenkins
RUN BUILD_HADOOP=false /tmp/build-h2o-3
USER root
