ARG GPU_SUFFIX=''
ARG FROM_VERSION
FROM docker.h2o.ai/opsh2oai/h2o-3/dev-jdk-others-base${GPU_SUFFIX}:${FROM_VERSION}

ARG JAVA_VERSION
ENV JAVA_VERSION=${JAVA_VERSION}
COPY scripts/java-${JAVA_VERSION}-vars.sh scripts/java-${JAVA_VERSION}-vars.sh scripts/install_java_version_local jdk1.7.0_80.zip /tmp/
RUN \
    chmod +x /tmp/java-${JAVA_VERSION}-vars.sh && \
    sync && \
    if [ "${JAVA_VERSION}" = '7' ]; then \
        /tmp/install_java_version_local ${JAVA_VERSION} /tmp/java-${JAVA_VERSION}-vars.sh; \
    else \
        /tmp/install_java_version ${JAVA_VERSION} /tmp/java-${JAVA_VERSION}-vars.sh; \
    fi && \
    rm /tmp/install_java_version /tmp/install_java_version_local /tmp/java-${JAVA_VERSION}-vars.sh /tmp/jdk1.7.0_80.zip && \
    chmod a+w /usr/lib/jvm/

ENV \
  JAVA_HOME=/usr/lib/jvm/java-${JAVA_VERSION}-oracle \
  PATH=/usr/lib/jvm/java-${JAVA_VERSION}-oracle/bin:${PATH}
