ARG FROM_VERSION
FROM harbor.h2o.ai/opsh2oai/h2o-3/dev-python-3.6${GPU_SUFFIX}:${FROM_VERSION}

# Install Java 7 (and make it default) next to the Java contained in the Python 3.6 image
ENV JAVA_VERSION='1.7.0'
COPY scripts/install_java_version_open_jdk /tmp/
RUN \
    chmod +x /tmp/install_java_version_open_jdk && \
    sync && \
    /tmp/install_java_version_open_jdk 1.7.0 7 && \
    rm /tmp/install_java_version_open_jdk && \
    chmod a+w /usr/lib/jvm/

ENV \
  JAVA_HOME=/usr/lib/jvm/java-${INSTALL_JAVA_VERSION}-openjdk-amd64/ \
  PATH=/usr/lib/jvm/java-${INSTALL_JAVA_VERSION}-openjdk-amd64/bin:${PATH}
