ARG FROM_VERSION
FROM 353750902984.dkr.ecr.us-east-1.amazonaws.com/h2o-3/dev-python-3.7:${FROM_VERSION}

# Prepare packages to be able to build R from sources
RUN \
    sed -i.bak "/^#.*deb-src.*universe$/s/^# //g" /etc/apt/sources.list && \
    apt-get update && \
    mkdir -p /usr/share/man/man1 && \
    DEBIAN_FRONTEND=noninteractive apt -y build-dep r-base

# For rgl R package
RUN \
    apt-get install -y zip libglu1-mesa-dev libpcre2-dev

# Remove unnecessary packages
RUN \
    apt-get -y remove openjdk-8-jdk openjdk-8-jdk-headless openjdk-8-jre openjdk-8-jre-headless && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/cache/apt/*

# Install pandoc
RUN \
    wget https://github.com/jgm/pandoc/releases/download/2.1.1/pandoc-2.1.1-linux.tar.gz && \
    tar -xvzf pandoc-2.1.1-linux.tar.gz --strip-components 1 -C /usr/local/ && \
    rm -rf pandoc-2.1.1-linux.tar.gz
