
ARG FROM_VERSION
FROM 353750902984.dkr.ecr.us-east-1.amazonaws.com/h2o-3/dev-python-base:${FROM_VERSION}

ARG H2O_BRANCH=master
ARG PYTHON_VERSION
ENV PYTHON_VERSION=${PYTHON_VERSION}

RUN rm /tmp/install_python_version || true && \
    wget -nv https://raw.githubusercontent.com/h2oai/h2o-3/${H2O_BRANCH}/docker/scripts/install_python_version -O /tmp/install_python_version && \
    chmod +x /tmp/install_python_version
RUN \
    /tmp/install_python_version ${PYTHON_VERSION}
