FROM ubuntu:20.04

RUN apt-get update \
	&& apt-get install curl apt-utils unzip make jq gettext-base -y

RUN curl -fsSL https://get.docker.com -o get-docker.sh \
	&& sh get-docker.sh \
	&& usermod -aG docker root

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl \
	&& chmod +x ./kubectl \
	&& mv ./kubectl /usr/local/bin/kubectl

RUN curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | TAG=v1.7.0 bash

RUN curl https://baltocdn.com/helm/signing.asc | apt-key add - \
    && apt-get install apt-transport-https --yes \
    && echo "deb https://baltocdn.com/helm/stable/debian/ all main" | tee /etc/apt/sources.list.d/helm-stable-debian.list \
    && apt-get update \
    && apt-get install helm

RUN rm /var/lib/apt/lists -rf

RUN \
    groupadd -g $(id -g jenkins) jenkins && \
    adduser --uid $(id -u jenkins) -gid $(id -g jenkins) --disabled-password --gecos "" jenkins
    
CMD \
  ["/bin/bash"]
