ARG FROM_VERSION
FROM harbor.h2o.ai/opsh2oai/h2o-3/dev-r-3.4.1:${FROM_VERSION}

ENV NODE_MAJOR '16'

RUN apt-get update && apt-get install -y ca-certificates curl gnupg &&  mkdir -p /etc/apt/keyrings && \
curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --no-tty --yes --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
DEBIAN_FRONTEND=noninteractive apt-get install -y \
    nodejs \
    texlive \
    texlive-fonts-extra \
    texlive-latex-extra \
    texlive-latex-recommended \
    texlive-plain-generic \
    texinfo \
    texlive-bibtex-extra \
    texlive-formats-extra && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/cache/apt/*

COPY scripts/build-h2o-3 /tmp/
ARG H2O_BRANCH=master
RUN \
    chown jenkins:jenkins /tmp/build-h2o-3 && \
    chmod a+x /tmp/build-h2o-3 && \
    sync

# Set GRADLE USER env var
ENV GRADLE_OPTS='-Dorg.gradle.daemon=false'
# Warmup
USER jenkins
RUN BUILD_HADOOP=false /tmp/build-h2o-3
USER root
