ARG FROM_VERSION
FROM 353750902984.dkr.ecr.us-east-1.amazonaws.com/h2o-3/dev-python-3.7:${FROM_VERSION}

# Install Java 7 (and make it default) next to the Java contained in the Python 3.6 image
ENV JAVA_VERSION='1.7.0'
RUN \
    wget -nv https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz && \
    sync && \
    tar xzf openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz && \
    sync && \
    export PATH="${PWD}/java-se-7u75-ri/bin:$PATH"

ENV \
  JAVA_HOME=${PWD}/java-se-7u75-ri/ \
  PATH=${PWD}/java-se-7u75-ri/bin:${PATH}
