            ##
            # Author: Autogenerated on 2013-12-18 17:01:19
            # gitHash: 2581a0dfa12a51892283830529a5126ea49f0cb9
            # SEED: 2481425483200553751
            ##
            setwd(normalizePath(dirname(R.utils::commandArgs(asValues=TRUE)$"f")))
            source('../findNSourceUtils.R') 
            simpleFilterTest_stego_training_28 <- function(conn) {
                Log.info("A munge-task R unit test on data <stego_training> testing the functional unit <==> ")
                Log.info("Uploading stego_training")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/stego/stego_training.data"), "rstego_training.hex")
                Log.info("Filtering out rows by == from dataset stego_training and column \"118\" using value 0.0652700861753")
                     filterHex <- hex[hex[,c(118)] == 0.0652700861753,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C118" == 0.0652700861753,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"41\" using value 0.177056764273")
                     filterHex <- hex[hex[,c(41)] == 0.177056764273,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C41" == 0.177056764273,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"73\" using value 0.0299776482627")
                     filterHex <- hex[hex[,c(73)] == 0.0299776482627,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C73" == 0.0299776482627,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"12\" using value 0.0324090246436")
                     filterHex <- hex[hex[,c(12)] == 0.0324090246436,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C12" == 0.0324090246436,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"101\" using value 0.0710927414817")
                     filterHex <- hex[hex[,c(101)] == 0.0710927414817,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C101" == 0.0710927414817,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"137\" using value 0.0537514075556")
                     filterHex <- hex[hex[,c(137)] == 0.0537514075556,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C137" == 0.0537514075556,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"79\" using value 0.153820032498")
                     filterHex <- hex[hex[,c(79)] == 0.153820032498,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C79" == 0.153820032498,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"16\" using value 0.0583329926999")
                     filterHex <- hex[hex[,c(16)] == 0.0583329926999,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C16" == 0.0583329926999,]
                Log.info("Filtering out rows by == from dataset stego_training and column \"0\" using value 399.162211968")
                     filterHex <- hex[hex[,c(1)] == 399.162211968,]
                    Log.info("Perform filtering with the '$' sign also")
                Log.info("Filtering out rows by == from dataset stego_training and column \"26\" using value 0.114763398012")
                     filterHex <- hex[hex[,c(26)] == 0.114763398012,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C26" == 0.114763398012,]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"72\" using value 0.0285598421838, and also subsetting columns.")
                     filterHex <- hex[hex[,c(72)] == 0.0285598421838, c(72)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(72)] == 0.0285598421838, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"130\" using value 0.129214543548, and also subsetting columns.")
                     filterHex <- hex[hex[,c(130)] == 0.129214543548, c(130)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(130)] == 0.129214543548, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"63\" using value 0.0668372624189, and also subsetting columns.")
                     filterHex <- hex[hex[,c(63)] == 0.0668372624189, c(63)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(63)] == 0.0668372624189, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"5\" using value 0.13239000808, and also subsetting columns.")
                     filterHex <- hex[hex[,c(5)] == 0.13239000808, c(5)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(5)] == 0.13239000808, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"84\" using value 0.156383278611, and also subsetting columns.")
                     filterHex <- hex[hex[,c(84)] == 0.156383278611, c(84)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(84)] == 0.156383278611, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"76\" using value 0.0505294613643, and also subsetting columns.")
                     filterHex <- hex[hex[,c(76)] == 0.0505294613643, c(76)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(76)] == 0.0505294613643, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"143\" using value 0.17068292486, and also subsetting columns.")
                     filterHex <- hex[hex[,c(143)] == 0.17068292486, c(143)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(143)] == 0.17068292486, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"0\" using value 2247.32115604, and also subsetting columns.")
                     filterHex <- hex[hex[,c(1)] == 2247.32115604, c(1)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(1)] == 2247.32115604, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"149\" using value 0.0810640193438, and also subsetting columns.")
                     filterHex <- hex[hex[,c(149)] == 0.0810640193438, c(149)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(149)] == 0.0810640193438, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by == from dataset stego_training and column \"69\" using value 0.0534768718308, and also subsetting columns.")
                     filterHex <- hex[hex[,c(69)] == 0.0534768718308, c(69)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(69)] == 0.0534768718308, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
            testEnd()
            }
            doTest("simpleFilterTest_ on data stego_training unit= ==", simpleFilterTest_stego_training_28)
