            ##
            # Author: Autogenerated on 2013-12-18 17:01:19
            # gitHash: 2581a0dfa12a51892283830529a5126ea49f0cb9
            # SEED: 2481425483200553751
            ##
            setwd(normalizePath(dirname(R.utils::commandArgs(asValues=TRUE)$"f")))
            source('../findNSourceUtils.R') 
            simpleFilterTest_stego_testing_25 <- function(conn) {
                Log.info("A munge-task R unit test on data <stego_testing> testing the functional unit <>=> ")
                Log.info("Uploading stego_testing")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/stego/stego_testing.data"), "rstego_testing.hex")
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"140\" using value 0.0892707366817")
                     filterHex <- hex[hex[,c(140)] >= 0.0892707366817,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C140" >= 0.0892707366817,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"32\" using value 0.231234377862")
                     filterHex <- hex[hex[,c(32)] >= 0.231234377862,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C32" >= 0.231234377862,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"68\" using value 0.0888510352114")
                     filterHex <- hex[hex[,c(68)] >= 0.0888510352114,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C68" >= 0.0888510352114,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"131\" using value 0.334062868422")
                     filterHex <- hex[hex[,c(131)] >= 0.334062868422,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C131" >= 0.334062868422,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"41\" using value 0.0481030331377")
                     filterHex <- hex[hex[,c(41)] >= 0.0481030331377,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C41" >= 0.0481030331377,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"101\" using value 0.0359644755278")
                     filterHex <- hex[hex[,c(101)] >= 0.0359644755278,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C101" >= 0.0359644755278,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"95\" using value 0.139419130855")
                     filterHex <- hex[hex[,c(95)] >= 0.139419130855,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C95" >= 0.139419130855,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"64\" using value 0.0207348242717")
                     filterHex <- hex[hex[,c(64)] >= 0.0207348242717,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C64" >= 0.0207348242717,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"137\" using value 0.0720152823062")
                     filterHex <- hex[hex[,c(137)] >= 0.0720152823062,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C137" >= 0.0720152823062,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"130\" using value 0.0875441157709")
                     filterHex <- hex[hex[,c(130)] >= 0.0875441157709,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C130" >= 0.0875441157709,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"134\" using value 0.0213378833745")
                     filterHex <- hex[hex[,c(134)] >= 0.0213378833745,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C134" >= 0.0213378833745,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"150\" using value 0.208177355341")
                     filterHex <- hex[hex[,c(150)] >= 0.208177355341,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C150" >= 0.208177355341,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"126\" using value 0.0610954483328")
                     filterHex <- hex[hex[,c(126)] >= 0.0610954483328,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C126" >= 0.0610954483328,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"10\" using value 0.288951496822")
                     filterHex <- hex[hex[,c(10)] >= 0.288951496822,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C10" >= 0.288951496822,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"143\" using value 0.0475153109497")
                     filterHex <- hex[hex[,c(143)] >= 0.0475153109497,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C143" >= 0.0475153109497,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"13\" using value 0.0288878640019")
                     filterHex <- hex[hex[,c(13)] >= 0.0288878640019,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C13" >= 0.0288878640019,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"122\" using value 0.222543954718")
                     filterHex <- hex[hex[,c(122)] >= 0.222543954718,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C122" >= 0.222543954718,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"64\" using value 0.00696241333679")
                     filterHex <- hex[hex[,c(64)] >= 0.00696241333679,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C64" >= 0.00696241333679,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"144\" using value 0.0506679859339")
                     filterHex <- hex[hex[,c(144)] >= 0.0506679859339,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C144" >= 0.0506679859339,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"121\" using value 0.0287894228539")
                     filterHex <- hex[hex[,c(121)] >= 0.0287894228539,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C121" >= 0.0287894228539,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"136\" using value 0.0294970295901")
                     filterHex <- hex[hex[,c(136)] >= 0.0294970295901,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C136" >= 0.0294970295901,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"107\" using value 0.113350394775")
                     filterHex <- hex[hex[,c(107)] >= 0.113350394775,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C107" >= 0.113350394775,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"115\" using value 0.0576453541341")
                     filterHex <- hex[hex[,c(115)] >= 0.0576453541341,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C115" >= 0.0576453541341,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"44\" using value 0.0895010282548")
                     filterHex <- hex[hex[,c(44)] >= 0.0895010282548,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C44" >= 0.0895010282548,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"39\" using value 0.0749186976044")
                     filterHex <- hex[hex[,c(39)] >= 0.0749186976044,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C39" >= 0.0749186976044,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"143\" using value 0.0589294146148")
                     filterHex <- hex[hex[,c(143)] >= 0.0589294146148,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C143" >= 0.0589294146148,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"15\" using value 0.0491452268657")
                     filterHex <- hex[hex[,c(15)] >= 0.0491452268657,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C15" >= 0.0491452268657,]
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"0\" using value 10738.3292973")
                     filterHex <- hex[hex[,c(1)] >= 10738.3292973,]
                    Log.info("Perform filtering with the '$' sign also")
                Log.info("Filtering out rows by >= from dataset stego_testing and column \"22\" using value 0.174958892429")
                     filterHex <- hex[hex[,c(22)] >= 0.174958892429,]
                    Log.info("Perform filtering with the '$' sign also")
                    filterHex <- hex[hex$"C22" >= 0.174958892429,]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"93\" using value 0.128368497897, and also subsetting columns.")
                     filterHex <- hex[hex[,c(93)] >= 0.128368497897, c(93)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(93)] >= 0.128368497897, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"137\" using value 0.0426466225673, and also subsetting columns.")
                     filterHex <- hex[hex[,c(137)] >= 0.0426466225673, c(137)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(137)] >= 0.0426466225673, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"147\" using value 0.270138949853, and also subsetting columns.")
                     filterHex <- hex[hex[,c(147)] >= 0.270138949853, c(147)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(147)] >= 0.270138949853, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"76\" using value 0.0650364800874, and also subsetting columns.")
                     filterHex <- hex[hex[,c(76)] >= 0.0650364800874, c(76)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(76)] >= 0.0650364800874, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"121\" using value 0.0609248564033, and also subsetting columns.")
                     filterHex <- hex[hex[,c(121)] >= 0.0609248564033, c(121)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(121)] >= 0.0609248564033, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"15\" using value 0.0862729728208, and also subsetting columns.")
                     filterHex <- hex[hex[,c(15)] >= 0.0862729728208, c(15)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(15)] >= 0.0862729728208, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"61\" using value 0.17961984063, and also subsetting columns.")
                     filterHex <- hex[hex[,c(61)] >= 0.17961984063, c(61)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(61)] >= 0.17961984063, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"64\" using value 0.035848840038, and also subsetting columns.")
                     filterHex <- hex[hex[,c(64)] >= 0.035848840038, c(64)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(64)] >= 0.035848840038, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"54\" using value 0.050601259496, and also subsetting columns.")
                     filterHex <- hex[hex[,c(54)] >= 0.050601259496, c(54)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(54)] >= 0.050601259496, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"43\" using value 0.182987530729, and also subsetting columns.")
                     filterHex <- hex[hex[,c(43)] >= 0.182987530729, c(43)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(43)] >= 0.182987530729, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"135\" using value 0.010677274231, and also subsetting columns.")
                     filterHex <- hex[hex[,c(135)] >= 0.010677274231, c(135)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(135)] >= 0.010677274231, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"121\" using value 0.0998702784202, and also subsetting columns.")
                     filterHex <- hex[hex[,c(121)] >= 0.0998702784202, c(121)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(121)] >= 0.0998702784202, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"140\" using value 0.397811379516, and also subsetting columns.")
                     filterHex <- hex[hex[,c(140)] >= 0.397811379516, c(140)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(140)] >= 0.397811379516, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"147\" using value 0.236997472902, and also subsetting columns.")
                     filterHex <- hex[hex[,c(147)] >= 0.236997472902, c(147)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(147)] >= 0.236997472902, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"2\" using value 0.166846718146, and also subsetting columns.")
                     filterHex <- hex[hex[,c(2)] >= 0.166846718146, c(2)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(2)] >= 0.166846718146, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"12\" using value 0.138828726629, and also subsetting columns.")
                     filterHex <- hex[hex[,c(12)] >= 0.138828726629, c(12)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(12)] >= 0.138828726629, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"146\" using value 0.0264026632182, and also subsetting columns.")
                     filterHex <- hex[hex[,c(146)] >= 0.0264026632182, c(146)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(146)] >= 0.0264026632182, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"147\" using value 0.0705891651876, and also subsetting columns.")
                     filterHex <- hex[hex[,c(147)] >= 0.0705891651876, c(147)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(147)] >= 0.0705891651876, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"96\" using value 0.109413668682, and also subsetting columns.")
                     filterHex <- hex[hex[,c(96)] >= 0.109413668682, c(96)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(96)] >= 0.109413668682, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"66\" using value 0.0379985483514, and also subsetting columns.")
                     filterHex <- hex[hex[,c(66)] >= 0.0379985483514, c(66)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(66)] >= 0.0379985483514, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"150\" using value 0.0331187200947, and also subsetting columns.")
                     filterHex <- hex[hex[,c(150)] >= 0.0331187200947, c(150)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(150)] >= 0.0331187200947, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"139\" using value 0.335253101895, and also subsetting columns.")
                     filterHex <- hex[hex[,c(139)] >= 0.335253101895, c(139)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(139)] >= 0.335253101895, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"104\" using value 0.106704236017, and also subsetting columns.")
                     filterHex <- hex[hex[,c(104)] >= 0.106704236017, c(104)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(104)] >= 0.106704236017, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"115\" using value 0.321191669885, and also subsetting columns.")
                     filterHex <- hex[hex[,c(115)] >= 0.321191669885, c(115)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(115)] >= 0.321191669885, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"129\" using value 0.0847687937601, and also subsetting columns.")
                     filterHex <- hex[hex[,c(129)] >= 0.0847687937601, c(129)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(129)] >= 0.0847687937601, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"126\" using value 0.042187337604, and also subsetting columns.")
                     filterHex <- hex[hex[,c(126)] >= 0.042187337604, c(126)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(126)] >= 0.042187337604, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"46\" using value 0.00607342170374, and also subsetting columns.")
                     filterHex <- hex[hex[,c(46)] >= 0.00607342170374, c(46)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(46)] >= 0.00607342170374, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"29\" using value 0.0335007684713, and also subsetting columns.")
                     filterHex <- hex[hex[,c(29)] >= 0.0335007684713, c(29)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(29)] >= 0.0335007684713, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
                    Log.info("Filtering out rows by >= from dataset stego_testing and column \"101\" using value 0.0175911118095, and also subsetting columns.")
                     filterHex <- hex[hex[,c(101)] >= 0.0175911118095, c(101)]
                    Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[hex[,c(101)] >= 0.0175911118095, c(133,132,131,130,137,136,135,134,139,138,24,25,26,27,20,21,22,23,160,28,29,161,4,8,163,119,120,121,122,123,124,125,126,127,128,129,118,59,58,55,54,57,56,51,50,53,52,115,114,88,89,111,110,113,112,82,83,80,81,86,87,84,85,3,7,108,109,102,103,100,101,106,107,104,105,39,38,33,32,31,30,37,36,35,34,60,61,62,63,64,65,66,67,68,69,2,162,6,99,98,91,90,93,92,95,94,97,96,11,10,13,12,15,14,17,16,19,18,117,116,151,150,153,152,155,154,157,156,159,158,48,49,46,47,44,45,42,43,40,41,1,5,9,146,147,144,145,142,143,140,141,148,149,77,76,75,74,73,72,71,70,79,78)]
            testEnd()
            }
            doTest("simpleFilterTest_ on data stego_testing unit= >=", simpleFilterTest_stego_testing_25)
