            ##
            # Author: Autogenerated on 2013-12-18 17:01:19
            # gitHash: 2581a0dfa12a51892283830529a5126ea49f0cb9
            # SEED: 2481425483200553751
            ##
            setwd(normalizePath(dirname(R.utils::commandArgs(asValues=TRUE)$"f")))
            source('../findNSourceUtils.R')
            complexFilterTest_iris_train_41 <- function(conn) {
                Log.info("A munge-task R unit test on data <iris_train> testing the functional unit <['!', '!=', '&', '>=', '|', '>=']> ")
                Log.info("Uploading iris_train")
                hex <- h2o.uploadFile(conn, locate("../../smalldata/iris/iris_train.csv"), "riris_train.hex")
            Log.info("Performing compound task !( ( hex[,c(\"petal_len\")] != 6.49447592076 ) & ( hex[,c(\"petal_wid\")] >= 1.55410879616 ) | ( ( hex[,c(\"petal_wid\")] >= 1.11130252696 )) ) on dataset <iris_train>")
                     filterHex <- hex[!( ( hex[,c("petal_len")] != 6.49447592076 ) & ( hex[,c("petal_wid")] >= 1.55410879616 ) | ( ( hex[,c("petal_wid")] >= 1.11130252696 )) ),]
            Log.info("Performing compound task !( ( hex[,c(\"petal_len\")] != 3.0640573885 ) & ( hex[,c(\"sepal_wid\")] >= 2.14442276314 ) | ( ( hex[,c(\"petal_wid\")] >= 0.555791134075 )) ) on dataset iris_train, and also subsetting columns.")
                     filterHex <- hex[!( ( hex[,c("petal_len")] != 3.0640573885 ) & ( hex[,c("sepal_wid")] >= 2.14442276314 ) | ( ( hex[,c("petal_wid")] >= 0.555791134075 )) ), c("petal_wid","sepal_wid","petal_len","sepal_len")]
                Log.info("Now do the same filter & subset, but select complement of columns.")
                     filterHex <- hex[!( ( hex[,c("petal_len")] != 3.0640573885 ) & ( hex[,c("sepal_wid")] >= 2.14442276314 ) | ( ( hex[,c("petal_wid")] >= 0.555791134075 )) ), c("species")]
            testEnd()
            }
            doTest("compoundFilterTest_ on data iris_train unit= ['!', '!=', '&', '>=', '|', '>=']", complexFilterTest_iris_train_41)
