setwd(normalizePath(dirname(R.utils::commandArgs(asValues=TRUE)$"f")))
source("../../scripts/h2o-r-test-setup.R")
##
# Author: Autogenerated on 2013-12-18 17:01:19
# gitHash: 2581a0dfa12a51892283830529a5126ea49f0cb9
# SEED: 2481425483200553751
##



complexFilterTest_benign_37 <- function() {
    h2oTest.logInfo("A munge-task R unit test on data <benign> testing the functional unit <['', '<=']> ")
    h2oTest.logInfo("Uploading benign")
    hex <- h2o.importFile(h2oTest.locate("smalldata/logreg/benign.csv"), "rbenign.hex")
h2oTest.logInfo("Performing compound task ( ( hex[,c(\"WT\")] <= 277.042893399 ))  on dataset <benign>")
         filterHex <- hex[( ( hex[,c("WT")] <= 277.042893399 )) ,]
h2oTest.logInfo("Performing compound task ( ( hex[,c(\"MST\")] <= 2.04621771039 ))  on dataset benign, and also subsetting columns.")
         filterHex <- hex[( ( hex[,c("MST")] <= 2.04621771039 )) , c("MST","AGMT","AGP1","DEG","WT","AGLP","OBS","STR")]
    h2oTest.logInfo("Now do the same filter & subset, but select complement of columns.")
         filterHex <- hex[( ( hex[,c("MST")] <= 2.04621771039 )) , c("HIGD","FNDX","NLV","AGMN","CHK","LIV")]

}
h2oTest.doTest("compoundFilterTest_ on data benign unit= ['', '<=']", complexFilterTest_benign_37)
