#! /bin/bash

su - hdfs -c 'hadoop fs -mkdir -p /tmp/hadoop-yarn/staging/history/done_intermediate'
su - hdfs -c 'hadoop fs -chown -R mapred:mapred /tmp/hadoop-yarn/staging'
su - hdfs -c 'hadoop fs -chmod -R 1777 /tmp'
su - hdfs -c 'hadoop fs -mkdir -p /var/log/hadoop-yarn'
su - hdfs -c 'hadoop fs -chown yarn:mapred /var/log/hadoop-yarn'

chown mapred /var/log/hadoop-mapreduce
