module.exports = {
  defaultSidebar: [
    "index",
    {
      "Get started": ["get-started/overview", "installation"],
    },
    {
      Welcome: [
        "welcome",
        {
          "Getting started": [
            "getting-started/getting-started",
            "getting-started/python-users",
            "getting-started/r-users",
            "getting-started/flow-users",
            "getting-started/api-users",
            "getting-started/java-users",
            "getting-started/docker-users",
            "getting-started/experienced-users",
          ],
        },
        "api-changes",
        "quick-start-videos",
      ],
    },
    {
      "Using H2O-3": [
        "downloading",
        "starting-h2o",
        "h2o-client",
        "flow",
        "logs",
        "security",
        "telemetry",
        "architecture",
        "glossary",
        "additional-resources",
        "data-sources",
        "docker",
      ],
    },
    {
      "Modeling": [
        "training-models",
        "cross-validation",
        "checkpointing-models",
        "grid-search",
        "performance-and-prediction",
        "variable-importance",
        "automl",
        "explain",
        "admissible",
      ],
    },
    {
      "Production": [
        "save-and-load-model",
        "productionizing",
        "mojo-quickstart",
        "mojo-capabilities",
        "pojo-quickstart",
      ],
    },
    {
      FAQ: [
        "faq/general",
        "faq/algorithms",
        "faq/clusters",
        "faq/data",
        "faq/python",
        "faq/r",
        "faq/java",
        "faq/flow",
        "faq/building-h2o",
        "faq/general-troubleshooting",
        "faq/tunneling",
      ],
    },
    {
      "Data manipulation": [
        "data-munging/uploading-data",
        "data-munging/importing-data",
        "data-munging/importing-files",
        "data-munging/downloading-data",
        "data-munging/change-column-type",
        "data-munging/combining-columns",
        "data-munging/combining-rows",
        "data-munging/fillnas",
        "data-munging/groupby",
        "data-munging/imputing-data",
        "data-munging/merging-data",
        "data-munging/pivot",
        "data-munging/replacing-values",
        "data-munging/slicing-columns",
        "data-munging/slicing-rows",
        "data-munging/sortcolumn",
        "data-munging/splitting-datasets",
        "data-munging/tokenize",
      ],
    },
    "release-notes",
  ],
};
