#! /bin/bash

set -e
set -x

JRE_FILE='jdk-8u172-linux-x64.rpm'
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
"http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/${JRE_FILE}"
rpm --rebuilddb
yum localinstall -y ${JRE_FILE}
rm ${JRE_FILE}

mkdir -p /usr/lib/jvm
ln -s -f /usr/java/default /usr/lib/jvm/java-8-oracle

echo "Creating activation script"
echo """ #! /bin/bash

rm -f /usr/lib/jvm/java-current-oracle
ln -s -f /usr/lib/jvm/java-8-oracle /usr/lib/jvm/java-current-oracle """ > /usr/bin/activate_java_8
chmod a+x /usr/bin/activate_java_8

/usr/bin/activate_java_8