#! /bin/bash

set -e
set -x

JRE_FILE='jdk-8u161-linux-x64.rpm'
wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" \
"http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/${JRE_FILE}"
rpm --rebuilddb
yum localinstall -y ${JRE_FILE}
rm ${JRE_FILE}

mkdir -p /usr/lib/jvm
ln -s -f /usr/java/default /usr/lib/jvm/java-8-oracle
