#!/bin/bash -ex

yum install -y http://opensource.wandisco.com/centos/6/git/x86_64/wandisco-git-release-6-1.noarch.rpm
rpm --rebuilddb
yum update -y nss
rpm --rebuilddb
yum update -y curl
rpm --rebuilddb
yum update -y libcurl
rpm --rebuilddb
yum install -y wget gcc gcc-c++ shadow-utils.x86_64
rpm --rebuilddb
yum -y install https://repo.ius.io/ius-release-el$(rpm -q --queryformat '%{VERSION}' centos-release).rpm
sed -i '/\[ius.*\]/a sslverify=0' /etc/yum.repos.d/ius.repo
rpm --rebuilddb
yum -y install python35u-devel python-pip python-virtualenv git mysql-devel unzip make tar zlib-devel libffi-devel

