#! /usr/bin/groovy

@Library('test-shared-library') _
import ai.h2o.ci.Utils

def utilsLib = new Utils()

pipeline {
  agent none

  parameters {
      string(name: 'version', description: 'CDH or HDP version')
      choice(
              choices: 'cdh\nhdp',
              description: 'Hadoop Distribution',
              name: 'distribution')
  }

  environment {
      BUILD_HADOOP = 'true'
  }

  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 60, unit: 'MINUTES')
    // lets keep 33 logs, because currently we test against 11 various hadoop versions
    buildDiscarder(logRotator(numToKeepStr: '33'))
  }

  stages {
    stage('Execute Tests') {
      agent {
        dockerfile {
          label "mr-0xc10"
          filename "h2o-hadoop/scripts/docker/${params.distribution}/Dockerfile"
          additionalBuildArgs "--build-arg VERSION=${params.version} --build-arg PATH_PREFIX=h2o-hadoop/scripts/docker/${params.distribution} --build-arg DEFAULT_USER_UID=\$(id -u)"
          args "-u root -v \${WORKSPACE}:/home/h2o/h2o-3 -v \${WORKSPACE}/h2o-hadoop/scripts/docker/common/custom_startup/:/startup/"
          reuseNode true
        }
      }
      steps {
        sh "/usr/sbin/startup.sh"
      }
    }
  }
}
