name: Nightly H2O-3 Build and Test

on:
  push:
    branches:
      - main
      - rel-*
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 21 * * *'  # rel- branches at 21:00 UTC

jobs:
  build-and-test:
    name: Checkout, Build, Health Check, and Test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      HEALTH_CHECK_RETRIES: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Retry Health Check and Build
        id: health_check_build
        run: |
          ATTEMPT=0
          PASSED=0
          while [ "$PASSED" -eq 0 ]; do
            ATTEMPT=$((ATTEMPT+1))
            if [ "$ATTEMPT" -gt "${{ env.HEALTH_CHECK_RETRIES }}" ]; then
              echo "Too many attempts to pass health check"
              exit 1
            fi

            echo "Attempt #$ATTEMPT: Health Checking and Building..."

            # Clean previous build directory
            rm -rf h2o-3 && mkdir h2o-3
            cd h2o-3

            # Re-checkout (redundant here since checkout already happened)
            echo "Re-checkout H2O-3"
            git clone --depth=1 "${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}" .

            echo "Running health check script..."
            # Replace this with actual health check logic/script
            ./scripts/github/health-check.sh || continue

            echo "Running build script..."
            # Replace this with actual build logic
            ./scripts/github/build.sh || exit 1

            PASSED=1
          done

      - name: Run Test Stages
        run: |
          echo "Running test stages..."
          # Replace this with actual test logic
          ./scripts/github/run-tests.sh

      - name: Set final status
        run: echo "SUCCESS"
