name: Build and Test H2O-3

on:
  push:
    branches:
      - devops/rohan/mig-h2o-3-nightly-pipeline-to-gha
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-h2o3:
    name: Build & Test H2O-3
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install grip tabulate requests wheel

      - name: Install R
        uses: r-lib/actions/setup-r@v2

      - name: Set R_LIBS_USER and create R library folder
        run: |
          echo "R_LIBS_USER=$HOME/R/library" >> $GITHUB_ENV
          mkdir -p "$HOME/R/library"

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("RCurl", "jsonlite", "statmod", "devtools", "roxygen2", "testthat"), repos="https://cloud.r-project.org")'

      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: "sts.amazonaws.com"
          aws-region: "us-east-1"
          role-session-name: "h2o-shared-service-prd"
          role-to-assume: "arn:aws:iam::851725263148:role/GitHub-OIDC-Role"

      - name: Sync smalldata from S3
        run: |
          mkdir -p smalldata
          aws s3 sync s3://h2o-public-test-data/smalldata/ ./smalldata/

      - name: Run Gradle Build (no clean)
        if: steps.set-status.outputs.result == 'success'
        run: ./gradlew --build-cache --parallel build -x test -x :h2o-r:buildPackageDocumentation -x :h2o-r:buildPKG -x :h2o-r:buildPKGClient -x :h2o-r:untar --warning-mode all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
            name: h2o-3-build
            path: |
                build/
                h2o-core/build/
                h2o-admissibleml/build/
                h2o-py/build/
                smalldata/
            retention-days: 1
