#! /bin/bash

HDP_VERSION=$(ls /usr/hdp/ | grep -e '^2\|^3')
echo "Generating mapred-site.xml for HDP ${HDP_VERSION}"

cat > ${HADOOP_CONF_DIR}/mapred-site.xml <<EOF
<configuration>
  <property>
    <name>mapreduce.framework.name</name>
    <value>yarn</value>
  </property>
</configuration>
EOF
